### ISSUE TITLE
ValueError in negative_sampler.query_batch() for tgbl-flight dataset

### ISSUE THREAD

**Issue by mdaniluk** [shenyangHuang/TGB#60]
While working with the tgbl-flight dataset, the function negative_sampler.query_batch() throws a ValueError stating that an edge is not in the validation set. This issue is specific to the tgbl-flight dataset; other datasets work fine.

Code snippet:
```
from tgb.linkproppred.dataset_pyg import PyGLinkPropPredDataset
from torch_geometric.loader import TemporalDataLoader

dataset = PyGLinkPropPredDataset(name='tgbl-flight', root="datasets")
val_mask = dataset.val_mask

data = dataset.get_TemporalData()
val_data = data[val_mask]

neg_sampler = dataset.negative_sampler
val_loader = TemporalDataLoader(val_data, batch_size=200)

neg_sampler = dataset.negative_sampler
dataset.load_val_ns()

batch = next(iter(val_loader))
neg_batch_list = neg_sampler.query_batch(batch.src, batch.dst, batch.t, split_mode="val")
```

Error message:
```
ValueError: The edge (12, 4, 1638144000) is not in the 'val' evaluation set! Please check the implementation.
```

**Comment by shenyangHuang** [comment]
Hi @mdaniluk,

I just tested the above code in version `0.9.0`, releasing today and didn't run into any error.
Can you update the package and run again the above code? 

Best,
Andy

**Comment by ponythewhite** [comment]
Unfortunately even with a fresh install of `py-tgb` at version `0.9.0`, removal of all previous dataset folders & a from scratch download of the dataset the issue persists:

```
Python 3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %pip show py-tgb
Name: py-tgb
Version: 0.9.0
Summary: Temporal Graph Benchmark project repo
Home-page: 
Author: shenyang Huang
Author-email: shenyang.huang@mail.mcgill.ca
License: 
Location: /home/jdabrowski/miniconda3/lib/python3.10/site-packages
Requires: clint, pandas, requests, scikit-learn, torch-geometric, tqdm
Required-by: 
Note: you may need to restart the kernel to use updated packages.

In [2]: import tgb
   ...: from tgb.linkproppred.dataset_pyg import PyGLinkPropPredDataset
   ...: from torch_geometric.loader import TemporalDataLoader
   ...: 
   ...: dataset = PyGLinkPropPredDataset(name='tgbl-flight', root="datasets")
   ...: val_mask = dataset.val_mask
   ...: 
   ...: data = dataset.get_TemporalData()
   ...: val_data = data[val_mask]
   ...: 
   ...: neg_sampler = dataset.negative_sampler
   ...: val_loader = TemporalDataLoader(val_data, batch_size=200)
   ...: 
   ...: neg_sampler = dataset.negative_sampler
   ...: dataset.load_val_ns()
   ...: 
   ...: batch = next(iter(val_loader))
   ...: neg_batch_list = neg_sampler.query_batch(batch.src, batch.dst, batch.t, split_mode="val")
Dataset tgbl-flight version 2 not found.
Please download the latest version of the dataset.
Will you download the dataset(s) now? (y/N)
y
Download started, this might take a while . . . 
Dataset title: tgbl-flight
Dataset directory is  /home/jdabrowski/miniconda3/lib/python3.10/site-packages/tgb/datasets/tgbl_flight
[################################] 1251730/1251730 - 00:01:34
Download completed 
Dataset directory is  /home/jdabrowski/miniconda3/lib/python3.10/site-packages/tgb/datasets/tgbl_flight
file not processed, generating processed file
number of lines counted 67169570
numpy allocated
67169571it [10:43, 104374.58it/s]
57422it [00:00, 1374978.30it/s]
57422it [00:00, 414133.83it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[2], line 18
     15 dataset.load_val_ns()
     17 batch = next(iter(val_loader))
---> 18 neg_batch_list = neg_sampler.query_batch(batch.src, batch.dst, batch.t, split_mode="val")

File ~/miniconda3/lib/python3.10/site-packages/tgb/linkproppred/negative_sampler.py:127, in NegativeEdgeSampler.query_batch(self, pos_src, pos_dst, pos_timestamp, split_mode)
    125 for pos_s, pos_d, pos_t in zip(pos_src, pos_dst, pos_timestamp):
    126     if (pos_s, pos_d, pos_t) not in self.eval_set[split_mode]:
--> 127         raise ValueError(
    128             f"The edge ({pos_s}, {pos_d}, {pos_t}) is not in the '{split_mode}' evaluation set! Please check the implementation."
    129         )
    130     else:
    131         neg_samples.append(
    132             [
    133                 int(neg_dst)
    134                 for neg_dst in self.eval_set[split_mode][(pos_s, pos_d, pos_t)]
    135             ]
    136         )

ValueError: The edge (12, 4, 1638144000) is not in the 'val' evaluation set! Please check the implementation.

```

Any ideas?

Best,

Jack

**Comment by shenyangHuang** [comment]
Hi Jack, 

I just ran the above script locally and didn't run into any error. Can you double check you have all the correct dataset files processed and downloaded? You should have the folllowing files in: 
`tgbenv/lib/python3.9/site-packages/tgb/datasets/tgbl_flight` folder 

- airport_node_feat_v2.csv  
- ml_tgbl-flight_node.pkl  
- tgbl-flight_edgelist_v2.csv  
- tgbl-flight_val_ns_v2.pkl
- ml_tgbl-flight_edge.pkl   
- ml_tgbl-flight.pkl       
- tgbl-flight_test_ns_v2.pkl   
- tgbl-flight.zip

**Comment by ponythewhite** [comment]
Hi Andy @shenyangHuang,

### I do have all the above files. Below are their sizes and md5 sums:
```
(tgb-flight) jack@gpu301:~/anaconda3/envs/tgb/lib/python3.10/site-packages/tgb/datasets/tgbl_flight$ ls -l | awk '{print $5, $9}'
 
3316870 airport_node_feat_v2.csv
8597705100 ml_tgbl-flight_edge.pkl
2903018 ml_tgbl-flight_node.pkl
3224140088 ml_tgbl-flight.pkl
2185268447 tgbl-flight_edgelist_v2.csv
1158027354 tgbl-flight_test_ns_v2.pkl
1173849038 tgbl-flight_val_ns_v2.pkl
1281770568 tgbl-flight.zip

(tgb-flight) jack@gpu301:~/anaconda3/envs/tgb/lib/python3.10/site-packages/tgb/datasets/tgbl_flight$ md5sum *
13c00f14ef2561485ebe59873e3f5e62  airport_node_feat_v2.csv
445587fffe6d623b4d051a8ffbe0ff3d  ml_tgbl-flight_edge.pkl
010c04d6a183074ee10472484a074e3d  ml_tgbl-flight_node.pkl
c4f87eb34665dfa89013be0f2dcc557e  ml_tgbl-flight.pkl
4155697e921ff0b490eb1b12c0988afa  tgbl-flight_edgelist_v2.csv
c82efd6691d5697c60ba6915aa2971e0  tgbl-flight_test_ns_v2.pkl
39efbec4d3c3ae8c7b9112281ea91e57  tgbl-flight_val_ns_v2.pkl
9fae50d9ebebabe4bbd98a56b1c7f276  tgbl-flight.zip
```

I believe that `.pkl` checksums may differ due to python versions, but `zip` and `csv` should be the same.

## I replicated the issue on 2 fresh machines, always the same result. Below are full replication instructions.

### Set up a fresh conda/miniconda env:
```
conda create -y --name tgb-flight python=3.10 ipython
source activate tgb-flight
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
pip install py-tgb
```

### Run this script (as a Python file or in ipython)
```
from tgb.linkproppred.dataset_pyg import PyGLinkPropPredDataset
from torch_geometric.loader import TemporalDataLoader

dataset = PyGLinkPropPredDataset(name='tgbl-flight', root="datasets")
val_mask = dataset.val_mask

data = dataset.get_TemporalData()
val_data = data[val_mask]

neg_sampler = dataset.negative_sampler
val_loader = TemporalDataLoader(val_data, batch_size=200)

neg_sampler = dataset.negative_sampler
dataset.load_val_ns()

batch = next(iter(val_loader))
for _ in range(100):
    neg_batch_list = neg_sampler.query_batch(batch.src, batch.dst, batch.t, split_mode="val")
```

#### For me the output is invariably the same:
```
ValueError: The edge (12, 4, 1638140400) is not in the 'val' evaluation set! Please check the implementation.
```

Hope this helps in pinpointing the issue!

Best,

Jack

**Comment by shenyangHuang** [comment]
Hi @mdaniluk,

Thanks for trying again. I think it might be best to schedule a quick zoom work session to debug together to see what might be causing this issue (as I don't get the same error from my end). Can you email me at `shenyang.huang@mail.mcgill.ca` and let's schedule a quick meeting next week or so to fix it if you are free.

**Comment by rusty1s** [comment]
I can reproduce this on my end.

**Comment by shenyangHuang** [comment]
The problem is caused by time zone difference, currently I am in EDT time zone thus when preprocessing the timestamp of the edges (`datetime.strptime(ts, TIME_FORMAT)` ), it is calculated in the EDT time zone, in a different time zone, the timestamp would be different. I have updated the `preprocess.py` in my branch to reflect this change, will apply the change in the next version

**Comment by shenyangHuang** [comment]
fixed in the recent PR into `main` branch

**Comment by mdaniluk** [comment]
@shenyangHuang 
The issue still persists.

Now, rather than encountering an error in the first validation batch, the issue arises midway through the evaluation process:

```
for batch in tqdm(val_loader):
    neg_batch_list = neg_sampler.query_batch(batch.src, batch.dst, batch.t, split_mode="val")
```

```

 54%|                                                                                                                                                                         | 27029/50496 [00:18<00:16, 1439.29it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 2
      1 for batch in tqdm(val_loader):
----> 2     neg_batch_list = neg_sampler.query_batch(batch.src, batch.dst, batch.t, split_mode="val")

File /data/mdaniluk/tgb/TGB/tgb/linkproppred/negative_sampler.py:127, in NegativeEdgeSampler.query_batch(self, pos_src, pos_dst, pos_timestamp, split_mode)
    125 for pos_s, pos_d, pos_t in zip(pos_src, pos_dst, pos_timestamp):
    126     if (pos_s, pos_d, pos_t) not in self.eval_set[split_mode]:
--> 127         raise ValueError(
    128             f"The edge ({pos_s}, {pos_d}, {pos_t}) is not in the '{split_mode}' evaluation set! Please check the implementation."
    129         )
    130     else:
    131         neg_samples.append(
    132             [
    133                 int(neg_dst)
    134                 for neg_dst in self.eval_set[split_mode][(pos_s, pos_d, pos_t)]
    135             ]
    136         )

ValueError: The edge (16524, 47, 1647234000) is not in the 'val' evaluation set! Please check the implementation.
```
